# Generated by Django 3.1.7 on 2021-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('mark', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255, null=True)),
                ('year', models.DateField(null=True)),
                ('engine', models.CharField(max_length=255, null=True)),
                ('seats', models.CharField(choices=[('leather', 'Leather'), ('textile', 'Textile')], max_length=32, null=True)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=32)),
                ('categories', models.CharField(choices=[('small', 'Small Cars'), ('family', 'Family Cars'), ('van', 'Van')], max_length=32)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
