# Generated by Django 3.1.7 on 2021-04-01 14:15

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='categories',
            field=django_mysql.models.EnumField(choices=[('small', 'Small Cars'), ('family', 'Family Cars'), ('van', 'Van')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=django_mysql.models.EnumField(choices=[('leather', 'Leather'), ('textile', 'Textile')], null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=django_mysql.models.EnumField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')]),
        ),
    ]
